# Generated by Django 6.0 on 2026-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS unique_auth_user_email
            ON auth_user (LOWER(email))
            WHERE email IS NOT NULL;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS unique_auth_user_email;
            """
        )
    ]
